import pandas as pd
import matplotlib.pyplot as plt

df1 = pd.read_csv('r1.csv')
df2 = pd.read_csv('r2.csv')
df3 = pd.read_csv('r3.csv')
df12 = pd.read_csv('r1r2.csv')
df13 = pd.read_csv('r1r3.csv')
df23 = pd.read_csv('r2r3.csv')
df123 = pd.read_csv('r1r2r3.csv')

plt.scatter(df1.index, df1['r1HitCount'])
plt.title('r1 Feature Identification')
plt.ylabel('Feature Intensity')
plt.xlabel('index')
plt.savefig('r1.png')
plt.clf()

plt.scatter(df2.index, df2['r2HitCount'])
plt.title('r2 Feature Identification')
plt.ylabel('Feature Intensity')
plt.xlabel('index')
plt.savefig('r2.png')
plt.clf()

plt.scatter(df3.index, df3['r3HitCount'])
plt.title('r3 Feature Identification')
plt.ylabel('Feature Intensity')
plt.xlabel('index')
plt.savefig('r3.png')
plt.clf()

plt.scatter(df12.index, df12['r1r2HitCount'])
plt.title('r1r2 Feature Identification')
plt.ylabel('Feature Intensity')
plt.xlabel('index')
plt.savefig('r1r2.png')
plt.clf()

plt.scatter(df13.index, df13['r1r3HitCount'])
plt.title('r1r3 Feature Identification')
plt.ylabel('Feature Intensity')
plt.xlabel('index')
plt.savefig('r1r3.png')
plt.clf()

plt.scatter(df23.index, df23['r2r3HitCount'])
plt.title('r2r3 Feature Identification')
plt.ylabel('Feature Intensity')
plt.xlabel('index')
plt.savefig('r2r3.png')
plt.clf()

plt.scatter(df123.index, df123['r1r2r3HitCount'])
plt.title('r1r2r3 Feature Identification')
plt.ylabel('Feature Intensity')
plt.xlabel('index')
plt.savefig('r1r2r3.png')
plt.clf()
